version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
  gateway:
    container_name: gateway_container
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../api-gateway/src:/app/src
    env_file: ../api-gateway/configs/.env
    environment:
      AUTH_SERVICE_URL: http://auth:3001
      TEACHER_SERVICE_URL: "http://teacher:3002"
      STUDENT_SERVICE_URL: "http://student:3003"
      USER_SERVICE_URL: "http://user:3004"
      CLIENT_URL: http://localhost:8000
  notification:
    container_name: notification_container
    build:
      context: ../notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ../notification/src:/app/src
    env_file: ../notification/configs/.env
    environment:
      RABBITMQ_ENDPOINT: amqp://myuser:mypassword@rabbitmq_container:5672
    depends_on:
      - rabbitmq
  auth:
    container_name: auth_container
    build:
      context: ../auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ../auth/src:/app/src
    env_file: ../auth/configs/.env
    environment:
      USER_SERVICE: http://user:3004
      RABBITMQ_ENDPOINT: amqp://myuser:mypassword@rabbitmq_container:5672
    depends_on:
      - rabbitmq

  user:
    container_name: user_container
    build:
      context: ../user
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3004:3004"
    volumes:
      - ../user/src:/app/src
    env_file: ../user/configs/.env
    environment:
      AUTH_SERVICE_GET: http://auth:3001

  student:
    container_name: student_container
    build:
      context: ../student
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ../student/src:/app/src
    env_file: ../student/configs/.env
    environment:
      USER_SERVICE: http://user:3004
  teacher:
    container_name: teacher_container
    build:
      context: ../teacher
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ../teacher/src:/app/src
    env_file: ../teacher/configs/.env
networks:
  default:
    driver: bridge
